use std::{
    any::Any,
    io::Write,
    marker::PhantomData,
    sync::{
        atomic::{AtomicBool, Ordering},
        mpsc::{Sender, SyncSender},
        Arc,
    },
};

use crate::{Message, Prompt};

/// Per-job generation parameters, merged over the server's config defaults.
///
/// `None` means "use the server's configured default". Carrying these on the job (instead of
/// mutating shared server config before `run_job`) is what makes concurrent requests with
/// different sampling settings safe: two jobs in flight through the batching channel each sample
/// with their own merged settings.
#[derive(Clone, Debug, Default, PartialEq)]
pub struct GenerationParams {
    /// Caps the number of generated tokens. Merged over the server's configured cap and can only
    /// LOWER it, never raise it (the server cap stays authoritative).
    pub max_tokens: Option<usize>,
    /// Overrides the configured sampling temperature.
    pub temperature: Option<f64>,
    /// Overrides the configured top-p probability threshold.
    pub top_p: Option<f64>,
    /// Per-request seed for reproducible sampling. `Some(0)` (like an unset seed over a `0`
    /// config default) means "draw a fresh random seed for this job".
    pub seed: Option<u64>,
}

/// Fire-once cancellation signal for an [inference job](InferenceJob).
///
/// Cloned into the [JobHandle] (and any caller that needs to signal disconnection, e.g. an HTTP
/// handler watching its SSE stream); observed by the engine executing the job.
#[derive(Clone, Debug, Default)]
pub struct CancelSignal(Arc<AtomicBool>);

impl CancelSignal {
    /// Signal cancellation. Idempotent; cannot be unset.
    pub fn cancel(&self) {
        self.0.store(true, Ordering::Relaxed);
    }

    /// Whether cancellation has been requested.
    pub fn is_cancelled(&self) -> bool {
        self.0.load(Ordering::Relaxed)
    }
}

/// Defines a job to be run during inference.
pub struct InferenceJob {
    /// The task to be performed by the job.
    pub task: InferenceTask,
    /// The emitter for the current job.
    pub emitter: GeneratedItemEmitter,
    /// Per-job generation parameters, merged over server config defaults.
    pub params: GenerationParams,
    /// Cancellation signal, shared with the [JobHandle].
    pub cancel: CancelSignal,
}

/// An emitter is responsible to send [generated items](GeneratedItem) to the [inference job](InferenceJob)
/// channel.
pub struct GeneratedItemEmitter {
    sender: Sender<Msg>,
    done: Arc<AtomicBool>,
}

/// The potential tasks that can be executed by an [inference job](InferenceJob) using the
/// [inference server](crate::InferenceServer).
pub enum InferenceTask {
    /// A single message to be processed by the server.
    Message(Message),
    /// Multiple messages to be processed by the server.
    ///
    /// This could be useful to restore a previous session based on text history.
    Context(Vec<Message>),
    /// Run with a simple prompt.
    Prompt(Prompt),
}

/// Defines all the potential items that can be generated by an [inference job](InferenceJob).
///
/// For now there is only text generation, but this could be extented to other kind of output
/// artifacts.
pub enum GeneratedItem {
    /// Generated text includes intermediary tokens and doesn't mark the end of a text generation
    /// job.
    Text(String),
}

impl InferenceJob {
    /// Start a new inference job and process it on another thread.
    ///
    /// When a task is performed for the current job, it should be registered using the
    /// [completed method](Self::completed).
    pub fn create<L: InferenceJobListener>(
        task: InferenceTask,
        params: GenerationParams,
        listener: L,
    ) -> (Self, JobHandle<L>) {
        let (emitter, handle) = GeneratedItemEmitter::init(listener);
        let cancel = handle.cancel_signal();

        (
            Self {
                task,
                emitter,
                params,
                cancel,
            },
            handle,
        )
    }
}

impl GeneratedItemEmitter {
    pub fn init<L: InferenceJobListener>(mut listener: L) -> (Self, JobHandle<L>) {
        // Unbounded on purpose. The batching worker streams every sequence's tokens inline on its
        // single thread, so a bounded channel here lets one slow consumer — a backpressured SSE
        // socket whose `on_text` write blocks — fill the buffer and wedge the worker's next `send`,
        // head-of-line blocking every other in-flight request. An unbounded channel makes `send`
        // never block; each job's output is capped by `max_gen_tokens`, so the buffer can't grow
        // without bound. Regression: `a_blocking_listener_must_not_stall_other_jobs`.
        let (sender, receiver) = std::sync::mpsc::channel::<Msg>();

        let handle = JobHandle {
            sender: sender.clone(),
            cancel: CancelSignal::default(),
            _c: PhantomData,
        };
        let done = Arc::new(AtomicBool::new(false));
        let emitter = GeneratedItemEmitter {
            sender,
            done: done.clone(),
        };

        // One listener thread per job, deliberately not a thread pool. This thread blocks in
        // `on_text` on the client's socket, so a bounded pool would let a few slow clients hold every
        // pool thread hostage and starve the rest — reintroducing the head-of-line stall the
        // unbounded channel above removes. Per-job threads isolate clients (a slow one ties up only
        // its own thread) at the cost of an unbounded thread count; the real fix for that is an async
        // drain with no blocking thread at all, not a pool. A connection timeout bounds it meanwhile.
        std::thread::spawn(move || {
            for msg in receiver {
                match msg {
                    Msg::Text(text) => listener.on_text(text),
                    Msg::Finished(c) => {
                        let result = listener.on_finished();
                        let result: Box<dyn Any + Send> = Box::new(result);
                        c.send(result).unwrap();
                        done.store(true, Ordering::Relaxed);
                        return;
                    }
                }
            }
        });

        (emitter, handle)
    }

    /// Register the completion of an [inference generation](InferenceGeneration).
    pub fn completed(&self, item: GeneratedItem) {
        if !self.done.load(Ordering::Relaxed) {
            let msg = match item {
                GeneratedItem::Text(text) => Msg::Text(text),
            };
            // The listener thread may already be gone — e.g. the client dropped its stream and the
            // writer's pipe broke, panicking the listener. A failed send must NOT panic the caller:
            // on the batching worker thread a single panic here would unwind and brick the channel
            // for every other client. Treat a closed channel as "stop delivering" and latch `done`
            // so we don't keep retrying for this job.
            if self.sender.send(msg).is_err() {
                self.done.store(true, Ordering::Relaxed);
            }
        }
    }
}

/// An inference job listener receive events while the [inference job](InferenceJob) is running.
pub trait InferenceJobListener: Send + 'static {
    /// The item that is returned by the listener.
    type CompletedItem: Send;

    /// Called when new text is generated from an [inference job](InferenceJob).
    fn on_text(&mut self, text: String);

    /// Called when the job is finished.
    ///
    /// The inference job listener can return an item when a job is finished.
    /// The item is going to be available through the [job handle finished method](JobHandle::finished).
    fn on_finished(self) -> Self::CompletedItem;
}

/// A listener that writes intermediary [generated items](GeneratedItem) to a writer as soon as
/// they are produced.
pub struct WriteListener<W: Write + Send + 'static> {
    writer: W,
}

impl<W: Write + Default + Send + 'static> Default for WriteListener<W> {
    fn default() -> Self {
        Self::new(W::default())
    }
}

impl<W: Write + Send + 'static> WriteListener<W> {
    pub fn new(writer: W) -> Self {
        Self { writer }
    }
}

impl<W: Write + Send + 'static> InferenceJobListener for WriteListener<W> {
    type CompletedItem = W;

    fn on_text(&mut self, text: String) {
        // The writer may be a client stream that has gone away (e.g. the HTTP client
        // dropped the SSE connection -> BrokenPipe). A failed write here must NOT panic:
        // this runs on the listener thread, and a panic kills it, which both bricks the
        // batch for every OTHER concurrent client and makes `join()` panic on the now-
        // closed channel. Swallow the error — the generation finishes normally and the
        // already-hardened `completed()` (closed-channel -> latch `done`) stops delivery.
        let _ = write!(self.writer, "{text}");
        let _ = self.writer.flush();
    }

    fn on_finished(self) -> Self::CompletedItem {
        self.writer
    }
}

#[derive(Default)]
/// The text generation listener accumulate the generated text in a string that can be
/// obtained at the end of the job with the [handle finished method](JobHandle::finished).
pub struct TextGenerationListener {
    inner: WriteListener<Vec<u8>>,
}

impl InferenceJobListener for TextGenerationListener {
    type CompletedItem = String;

    fn on_text(&mut self, text: String) {
        self.inner.on_text(text);
    }

    fn on_finished(self) -> Self::CompletedItem {
        String::from_utf8_lossy(&self.inner.on_finished()).into_owned()
    }
}

/// The stdout listener directly writes the intermediary [generated item](GeneratedItem) to
/// [std::io::stdout].
pub struct StdOutListener {
    inner: WriteListener<std::io::Stdout>,
}

impl Default for StdOutListener {
    fn default() -> Self {
        Self {
            inner: WriteListener::new(std::io::stdout()),
        }
    }
}

impl InferenceJobListener for StdOutListener {
    type CompletedItem = ();

    fn on_text(&mut self, text: String) {
        self.inner.on_text(text);
    }

    fn on_finished(self) -> Self::CompletedItem {}
}

/// The handle returned by [InferenceJob::start].
///
/// This handle should be used to indicate when a job is finished using the
/// [join method](JobHandle::join).
pub struct JobHandle<C: InferenceJobListener> {
    sender: Sender<Msg>,
    cancel: CancelSignal,
    _c: PhantomData<C>,
}

impl<C: InferenceJobListener> JobHandle<C> {
    /// Request cancellation of the job. Fire-once; the engine executing the job observes the
    /// token and stops generating.
    pub fn cancel(&self) {
        self.cancel.cancel();
    }

    /// A clone of the job's cancellation signal (e.g. to wire to a client disconnect signal).
    pub fn cancel_signal(&self) -> CancelSignal {
        self.cancel.clone()
    }

    /// Wait for the job to complete and returns the
    /// [InferenceJobListener::CompletedItem] from the job listener.
    ///
    /// # Warning
    ///
    /// Make sure to actually launch the inference job before calling this method, otherwise this
    /// method will never complete.
    pub fn join(&self) -> C::CompletedItem {
        let (sender, rec) = std::sync::mpsc::sync_channel(1);
        self.sender.send(Msg::Finished(sender)).unwrap();

        match rec.recv() {
            Ok(any) => *any.downcast().unwrap(),
            Err(err) => panic!("{err}"),
        }
    }
}

enum Msg {
    Text(String),
    Finished(SyncSender<Box<dyn Any + Send>>),
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The handle's token and the job's token are the SAME token (cancelling one is visible on
    /// the other), and cancellation is idempotent — fire-once, never unset.
    #[test]
    fn cancel_signal_is_shared_between_job_and_handle() {
        let (job, handle) = InferenceJob::create(
            InferenceTask::Prompt("p".to_string()),
            GenerationParams::default(),
            TextGenerationListener::default(),
        );
        assert!(!job.cancel.is_cancelled());
        handle.cancel();
        assert!(job.cancel.is_cancelled());
        handle.cancel();
        assert!(job.cancel.is_cancelled());
        // Drain the listener thread.
        drop(job);
        handle.join();
    }
}
